### ISSUE TITLE
Revivie your package

### ISSUE THREAD

**Issue by frozeman** [jeffmitchel/meteor-local-persist#1]
I would like to revive your package, as it seems fine to me. Either i will publish it under a new name, or you can add me as a collaborator, though i would like to change the name, to make it more findable (so i better publish a new one) :)

Just as a info

**Comment by jeffmitchel** [comment]
What name were you thinking of? I have found this package useful and was planning on upgrading it in the next few weeks.

**Comment by frozeman** [comment]
hi i actually forked it an released it under the name `persistent-minimongo` see https://atmospherejs.com/frozeman/persistent-minimongo

I also add a local storage cap, so that when the max size of 4.8 mb i met, it will remove the oldest 50 entries. As well as simplified the code. You now don't need to add a key, it will use the collection name instead.

**Comment by jeffmitchel** [comment]
Hi Fabian,

I decided to upgrade my package as well. Thanks for the kick!

Here’s what I did differently:
- I removed the dependency on Amplify and used localStorage directly. Following MDG lead on this.
- I didn’t do the cap check, instead I catch the exception when updating localStorage and call a user defined function to handle it. I also allow the setting of a maximum number of documents to track, which is handled the same as the storage full exception. You could probably implement your capping solution in that callback. I tried, but the browser (Canary) because unresponsive and had to be killed before I could fill the local storage.
- I did not remove the need for a key string, since _name is null for local collections.

Jeff

On January 28, 2015 at 10:17:27 AM, Fabian Vogelsteller (notifications@github.com) wrote:

hi i actually forked it an released it under the name persistent-minimongo see https://atmospherejs.com/frozeman/persistent-minimongo

I also add a local storage cap, so that when the max size of 4.8 mb i met, it will remove the oldest 50 entries. As well as simplified the code. You now don't need to add a key, it will use the collection name instead.

**Comment by frozeman** [comment]
Hey i didn't saw you answer back then :)

I just a few days ago released [persistent-minimongo2](https://github.com/frozeman/meteor-persistent-minimongo2), which uses the browsers indexedDB instead of localstorage.

**Comment by jeffmitchel** [comment]
Hi. Looks like you have a different use case in mind. Mine is reliable storage of small datasets, so localStorage makes sense for what I'm trying to do. The shopping cart example is actually pretty close to why it was originally implemented. I'd bee interested to hear how you are using your indexedDB package.

**Comment by frozeman** [comment]
Im working for ethereum a bitcoin 2.0 (or better 3.0) platform.
I develop Dapps, this are decentralised applications, which get their information only from the blockchain and have therefore no server.

So these dapps need to store some data in a DB, for faster retrieval and user settings.

Additionally you can build desktop applications using e.g. [electron](http://electron.atom.io). There you also need a DB and the local storage might be to small.

The main cause for me actually was, that when the browser crashes, it sometimes doesn't flush the local storage to disk and looses the data.

Using the indexedDB makes sure that data is always written to disk when changed.
